import type {Metadata} from 'next';
import Link from 'next/link';
import {PolicyPage} from '@/components/policy-page';
import {pageMetadata} from '@/lib/site';

export const metadata: Metadata=pageMetadata({title:'Privacy Notice',description:'How Living Yearbooks handles school content, photographs, enquiries and visitor privacy.',path:'/privacy'});

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Privacy" title="Privacy should be part of the yearbook—not an afterthought." introduction="This notice explains what the current Living Yearbooks prototype displays, what it does not collect, and the safeguards required before real school content is published.">
    <section><h2>1. Who this notice covers</h2><p>Living Yearbooks is a digital school-yearbook prototype for schools, students, families and invited visitors. The current demonstration uses fictional school information and fictional imagery. Before a real school is published, its content and permissions must be agreed with the school.</p></section>
    <section><h2>2. Information that may be published</h2><p>A published yearbook may contain a school name, branding, location, school photographs, graduating year, student names, portraits, class groups, quotes, biographies, activities, achievements and memories. Only information intended and approved for the yearbook should be entered.</p><p>Do not submit private records such as home addresses, student numbers, identity documents, medical information, academic records, passwords or private contact details.</p></section>
    <section><h2>3. Where content is stored</h2><p>Published yearbook content and optimized image assets are stored using Sanity, the content-management service used by this website. The public website reads published content without a write credential. Editing remains restricted to authenticated project members.</p></section>
    <section><h2>4. Enquiries</h2><p>When online enquiry delivery is enabled, the form sends the name, contact details, school, role and message you provide to the website server for validation and email delivery. Enquiry contents are not stored in the website database. The email provider and receiving business inbox process the message so it can be answered.</p><p>The protection system stores only a salted hash derived from the network address and a short-lived request counter. It does not store the enquiry alongside that counter. If email delivery has not yet been configured, the form will explain that online enquiries are unavailable and direct you to the contact details shown on the page.</p></section>
    <section><h2>5. Cookies and analytics</h2><p>The current website does not use advertising cookies or visitor analytics. Essential hosting and security systems may process technical request information needed to deliver and protect the website. If optional analytics are introduced, this notice and any required consent controls will be updated first.</p></section>
    <section><h2>6. Student photographs and permissions</h2><p>Schools are responsible for confirming that they have appropriate authority and permissions before providing names, photographs or stories for publication. Content should be limited to what is necessary for the yearbook and suitable for its intended audience.</p></section>
    <section><h2>7. Corrections and removal</h2><p>A student, parent or guardian, staff member, or authorized school representative may request that inaccurate material be corrected or that content be reviewed for removal. Use the <Link href="/contact">contact page</Link> and identify the school, yearbook and item concerned. Requests should not include additional sensitive information unless necessary.</p></section>
    <section><h2>8. Retention and changes</h2><p>Yearbooks are designed as long-term school archives, but publication is not a reason to retain inappropriate or unauthorized information. Retention arrangements for real schools will be agreed before launch. Material changes to these practices will be reflected on this page.</p></section>
    <aside><strong>Important:</strong> This prototype notice describes the current technical setup. It should receive appropriate legal review before the platform begins publishing real student information at scale.</aside>
  </PolicyPage>;
}
